drop database if exists dbpsicologhe;
create database if not exists dbpsicologhe;
use dbpsicologhe;
SET NAMES 'utf8';
create table questionari (
    idQuestionario int primary key not null auto_increment,
    nome varchar(100) not null 
);

create table domande(
    idDomanda int not null primary key auto_increment,
    testo varchar(300) not null,
	sessoDomanda char(1) not null,
    immagine varchar(255),
    codQuestionario int not null, 
    foreign key(codQuestionario) references questionari(idQuestionario)
);

create table opzioni(
    idOpzione int primary key auto_increment,
    testo varchar(50) not null
);

create table opzioniInDomande(
    idOpzioneInDomanda int primary key auto_increment,
    punteggio int not null,
    codDomanda int not null,
    foreign key(codDomanda) references domande(idDomanda),
    codOpzione int not null,
    foreign key(codOpzione) references opzioni(idOpzione)
);

create table utenti(
    idUtente int not null primary key auto_increment,
    cognome varchar(50) not null,
    nome varchar(50) not null,
    email varchar(255) not null,
    password char(32) not null,
    tipoUtente int not null,
    codPediatra int,
    foreign key(codPediatra) references utenti(idUtente)
);

create table figli(
    idFiglio int not null primary key auto_increment,
    cognome varchar(50) not null,
    nome varchar(50) not null,
    sesso char(1) not null,
    dataNascita date not null,
    codUtente int not null,
    foreign key(codUtente) references utenti(idUtente)
);

create table risposte(
    idRisposta int not null primary key auto_increment,
    dataOra datetime not null,
    codFiglio int not null,
    foreign key(codFiglio) references figli(idFiglio),
    codOpzioneInDomanda int not null,
    foreign key(codOpzioneInDomanda) references opzioniInDomande(idOpzioneInDomanda)
);

-- Questionario n.1: M-CHAT
insert into questionari(nome) values
("M-CHAT: Modified Checklist for Autism in Toddlers");

insert into domande(testo, codQuestionario, sessoDomanda) values
("Vostro figlio si diverte ad essere dondolato o a saltare sulle vostre ginocchia?", 1, 'M'),
("Vostra figlia si diverte ad essere dondolata o a saltare sulle vostre ginocchia?", 1, 'F'),
("Vostro figlio s'interessa agli altri bambini?", 1, 'M'),
("Vostra figlia s'interessa agli altri bambini?", 1, 'F'),
("A vostro figlio piace arrampicarsi sulle cose o sulle scale?", 1, 'M'),
("A vostra figlia piace arrampicarsi sulle cose o sulle scale?", 1, 'F'),
("Vostro figlio si diverte a giocare al gioco del CU-CU o a nascondino?", 1, 'M'),
("Vostra figlia si diverte a giocare al gioco del CU-CU o a nascondino?", 1, 'F'),
("Vostro figlio gioca mai a far finta? Per esempio fa finta di parlare al telefono o di accudire una bambola o altro?", 1, 'M'),
("Vostra figlia gioca mai a far finta? Per esempio fa finta di parlare al telefono o di accudire una bambola o altro?", 1, 'F'),
("Vostro figlio usa mai l'indicare col dito indice per chiedere qualcosa?", 1, 'M'),
("Vostra figlia usa mai l'indicare col dito indice per chiedere qualcosa?", 1, 'F'),
("Vostro figlio usa mai l'indicare col dito indice per segnalare interesse in qualcosa?", 1, 'M'),
("Vostra figlia usa mai l'indicare col dito indice per segnalare interesse in qualcosa?", 1, 'F'),
("Vostro figlio riesce a giocare in modo appropriato con piccoli giocattoli (ad esempio macchinine o cubi) e non solo portarli alla bocca o farli cadere?", 1, 'M'),
("Vostra figlia riesce a giocare in modo appropriato con piccoli giocattoli (ad esempio macchinine o cubi) e non solo portarli alla bocca o farli cadere?", 1, 'F'),
("Vostro figlio vi porta mai oggetti per mostrarvi qualcosa?", 1, 'M'),
("Vostra figlia vi porta mai oggetti per mostrarvi qualcosa?", 1, 'F'),
("Vostro figlio vi guarda negli occhi per più di un secondo o due?", 1, 'M'),
("Vostra figlia vi guarda negli occhi per più di un secondo o due?", 1, 'F'),
("Vostro figlio sembra mai ipersensibile ai rumori (ad es. tappandosi le orecchie)?", 1, 'M'),
("Vostra figlia sembra mai ipersensibile ai rumori (ad es. tappandosi le orecchie)?", 1, 'F'),
("Vostro figlio sorride in risposta alla vostra faccia o al vostro sorriso?", 1, 'M'),
("Vostra figlia sorride in risposta alla vostra faccia o al vostro sorriso?", 1, 'F'),
("Vostro figlio vi imita? (Ad esempio se fate una faccia lui cerca di imitarla?)", 1, 'M'),
("Vostra figlia vi imita? (Ad esempio se fate una faccia lui cerca di imitarla?)", 1, 'F'),
("Vostro figlio risponde al suo nome quando lo chiamate senza essere visti?", 1, 'M'),
("Vostra figlia risponde al suo nome quando la chiamate senza essere visti?", 1, 'F'),
("Se indicate con il dito indice un giocattolo dalla parte opposta della stanza, vostro figlio lo guarda?", 1, 'M'),
("Se indicate con il dito indice un giocattolo dalla parte opposta della stanza, vostra figlia lo guarda?", 1, 'F'),
("Vostro figlio cammina?", 1, 'M'),
("Vostra figlia cammina?", 1, 'F'),
("Vostro figlio guarda le cose a cui voi state guardando?", 1, 'M'),
("Vostra figlia guarda le cose a cui voi state guardando?", 1, 'F'),
("Vostro figlio fa movimenti inusuali con le dita davanti alla sua faccia?", 1, 'M'),
("Vostra figlia fa movimenti inusuali con le dita davanti alla sua faccia?", 1, 'F'),
("Vostro figlio cerca di attirare la vostra attenzione su una sua attività?", 1, 'M'),
("Vostra figlia cerca di attirare la vostra attenzione su una sua attività?", 1, 'F'),
("Vi siete mai chiesti se vostro figlio potesse essere sordo?", 1, 'M'),
("Vi siete mai chiesti se vostra figlia potesse essere sorda?", 1, 'F'),
("Vostro figlio capisce ciò che dicono le persone?", 1, 'M'),
("Vostra figlia capisce ciò che dicono le persone?", 1, 'F'),
("Vostro figlio qualche volta fissa lo sguardo nel vuoto o girovaga senza scopo?", 1, 'M'),
("Vostra figlia qualche volta fissa lo sguardo nel vuoto o girovaga senza scopo?", 1, 'F'),
("Vostro figlio vi guarda in faccia per capire quale è la vostra reazione di fronte a qualcosa di non familiare?", 1, 'M'),
("Vostra figlia vi guarda in faccia per capire quale è la vostra reazione di fronte a qualcosa di non familiare?", 1, 'F');

insert into opzioni(testo) values
("Si'"),
("No");

insert into opzioniInDomande(punteggio, codDomanda, codOpzione) values
(0, 1, 1),
(1, 1, 2),
(0, 2, 1),
(1, 2, 2),
(0, 3, 1),
(1, 3, 2),
(0, 4, 1),
(1, 4, 2),
(0, 5, 1),
(1, 5, 2),
(0, 6, 1),
(1, 6, 2),
(0, 7, 1),
(1, 7, 2),
(0, 8, 1),
(1, 8, 2),
(0, 9, 1),
(1, 9, 2),
(0, 10, 1),
(1, 10, 2),
(0, 11, 1),
(1, 11, 2),
(0, 12, 1),
(1, 12, 2),
(0, 13, 1),
(1, 13, 2),
(0, 14, 1),
(1, 14, 2),
(0, 15, 1),
(1, 15, 2),
(0, 16, 1),
(1, 16, 2),
(0, 17, 1),
(1, 17, 2),
(0, 18, 1),
(1, 18, 2),
(0, 19, 1),
(1, 19, 2),
(0, 20, 1),
(1, 20, 2),
(1, 21, 1),
(0, 21, 2),
(1, 22, 1),
(0, 22, 2),
(0, 23, 1),
(1, 23, 2),
(0, 24, 1),
(1, 24, 2),
(0, 25, 1),
(1, 25, 2),
(0, 26, 1),
(1, 26, 2),
(0, 27, 1),
(1, 27, 2),
(0, 28, 1),
(1, 28, 2),
(0, 29, 1),
(1, 29, 2),
(0, 30, 1),
(1, 30, 2),
(0, 31, 1),
(1, 31, 2),
(0, 32, 1),
(1, 32, 2),
(0, 33, 1),
(1, 33, 2),
(0, 34, 1),
(1, 34, 2),
(1, 35, 1),
(0, 35, 2),
(1, 36, 1),
(0, 36, 2),
(0, 37, 1),
(1, 37, 2),
(0, 38, 1),
(1, 38, 2),
(1, 39, 1),
(0, 39, 2),
(1, 40, 1),
(0, 40, 2),
(0, 41, 1),
(1, 41, 2),
(0, 42, 1),
(1, 42, 2),
(1, 43, 1),
(0, 43, 2),
(1, 44, 1),
(0, 44, 2),
(0, 45, 1),
(1, 45, 2),
(0, 46, 1),
(1, 46, 2);

-- Questionario n.2: Indicatori di abuso sessuale sui minori
insert into questionari(nome) values
("Indicatori di abuso sessuale sui minori");

insert into domande(testo, codQuestionario, sessoDomanda) values
("Il bambino dimostra conoscenze anomali per l'età di aspetti della sessualità adulta in bambini?", 2, 'M'),
("La bambina dimostra conoscenze anomali per l'età di aspetti della sessualità adulta in bambini?", 2, 'F'),
("Il bambino ha una certa tendenza all'erotizzazione dei rapporti come mezzo di socializzazione e per dare e ricevere affetto?", 2, 'M'),
("La bambina ha una certa tendenza all'erotizzazione dei rapporti come mezzo di socializzazione e per dare e ricevere affetto?", 2, 'F'),
("Il bambino avanza richieste di tipo sessuale agli adulti?", 2, 'M'),
("La bambina avanza richieste di tipo sessuale agli adulti?", 2, 'F'),
("Il bambino è alla ricerca compulsiva di giochi sessualizzati?", 2, 'M'),
("La bambina è alla ricerca compulsiva di giochi sessualizzati?", 2, 'F'),
("Il bambino è ideatore o partecipe dell'iniziazione sessuale di bambini più piccoli?", 2, 'M'),
("La bambina è ideatrice o partecipe dell'iniziazione sessuale di bambini più piccoli?", 2, 'F'),
("Il bambino crea disegni a contenuto sessuale?", 2, 'M'),
("La bambina crea disegni a contenuto sessuale?", 2, 'F'),
("Si osserva masturbazione compulsiva nel bambino?", 2, 'M'),
("Si osserva masturbazione compulsiva nella bambina?", 2, 'F'),
("Il bambino inserisce nell'ano corpi?", 2, 'M'),
("La bambina inserisce in vagina o nell'ano corpi?", 2, 'F'),
("Il bambino riporta arrossamenti, lividi, escoriazioni in area genitale e/o anale?", 2, 'M'),
("La bambina riporta arrossamenti, lividi, escoriazioni in area genitale e/o anale?", 2, 'F'),
("La bambina riporta perdite vaginali?", 2, 'F'),
("Sono presenti lividi sulle cosce e sulle braccia del bambino causati da contenzione manuale, da corde, ecc.?", 2, 'M'),
("Sono presenti lividi sulle cosce e sulle braccia della bambina causati da contenzione manuale, da corde, ecc.?", 2, 'F'),
("Il bambino presenta difficoltà a camminare o a sedersi?", 2, 'M'),
("La bambina presenta difficoltà a camminare o a sedersi?", 2, 'F'),
("Il bambino lamenta o riferisce dolore, bruciore dell'area ano-genitale?", 2, 'M'),
("La bambina lamenta o riferisce dolore, bruciore dell'area ano-genitale?", 2, 'F'),
("Il bambino mostra ritardi nello sviluppo fisico?", 2, 'M'),
("La bambina mostra ritardi nello sviluppo fisico?", 2, 'F');

insert into opzioniInDomande(punteggio, codDomanda, codOpzione) values
(1, 47, 1),
(0, 47, 2),
(1, 48, 1),
(0, 48, 2),
(1, 49, 1),
(0, 49, 2),
(1, 50, 1),
(0, 50, 2),
(1, 51, 1),
(0, 51, 2),
(1, 52, 1),
(0, 52, 2),
(1, 53, 1),
(0, 53, 2),
(1, 54, 1),
(0, 54, 2),
(1, 55, 1),
(0, 55, 2),
(1, 56, 1),
(0, 56, 2),
(1, 57, 1),
(0, 57, 2),
(1, 58, 1),
(0, 58, 2),
(1, 59, 1),
(0, 59, 2),
(1, 60, 1),
(0, 60, 2),
(1, 61, 1),
(0, 61, 2),
(1, 62, 1),
(0, 62, 2),
(1, 63, 1),
(0, 63, 2),
(1, 64, 1),
(0, 64, 2),
(1, 65, 1),
(0, 65, 2),
(1, 66, 1),
(0, 66, 2),
(1, 67, 1),
(0, 67, 2),
(1, 68, 1),
(0, 68, 2),
(1, 69, 1),
(0, 69, 2),
(1, 70, 1),
(0, 70, 2),
(1, 71, 1),
(0, 71, 2),
(1, 72, 1),
(0, 72, 2),
(1, 73, 1),
(0, 73, 2);